### ISSUE TITLE
Run unit tests and lint checks in CI

### ISSUE THREAD

**Issue by neilisaac** [joncrlsn/dque#11]
I recommend running https://github.com/golangci/golangci-lint on all projects since it has a good default set of lint checks which frequently uncover real issues.

Travis and Github Actions appear to have the best support for matrix builds (to run the tests on multiple go versions) so I'd recommend one of those.  I'm interested in trying Actions.  I also have a lot of experience using CircleCI but would mainly recommend it for teams with multiple repositories.  Any preference?

**Comment by joncrlsn** [comment]
Automated lint checking, etc would be great.  Github Actions looks good to me.  I have not used it before, but I assume it is free for open source projects on Github.

**Comment by neilisaac** [comment]
Yes, it's free for public repos.  

I also generally suggest configuring branch protection rules to prevent merging PRs that fail tests:

https://github.com/joncrlsn/dque/settings/branch_protection

![image](https://user-images.githubusercontent.com/111217/71675394-adce5880-2d4b-11ea-9b3c-45aa315189bc.png)
